var annotated_dup =
[
    [ "asyncpp", null, [
      [ "async_generator", "classasyncpp_1_1async__generator.html", null ],
      [ "async_launch_scope", "classasyncpp_1_1async__launch__scope.html", "classasyncpp_1_1async__launch__scope" ],
      [ "atomic_ref", "classasyncpp_1_1atomic__ref.html", "classasyncpp_1_1atomic__ref" ],
      [ "channel", "classasyncpp_1_1channel.html", "classasyncpp_1_1channel" ],
      [ "defer", "structasyncpp_1_1defer.html", "structasyncpp_1_1defer" ],
      [ "dispatcher", "classasyncpp_1_1dispatcher.html", "classasyncpp_1_1dispatcher" ],
      [ "exception_policy", "structasyncpp_1_1exception__policy.html", "structasyncpp_1_1exception__policy" ],
      [ "fiber", "classasyncpp_1_1fiber.html", "classasyncpp_1_1fiber" ],
      [ "fiber< void >", "classasyncpp_1_1fiber_3_01void_01_4.html", "classasyncpp_1_1fiber_3_01void_01_4" ],
      [ "generator", "classasyncpp_1_1generator.html", "classasyncpp_1_1generator" ],
      [ "intrusive_refcount", "classasyncpp_1_1intrusive__refcount.html", "classasyncpp_1_1intrusive__refcount" ],
      [ "latch", "classasyncpp_1_1latch.html", "classasyncpp_1_1latch" ],
      [ "multi_consumer_auto_reset_event", "classasyncpp_1_1multi__consumer__auto__reset__event.html", null ],
      [ "multi_consumer_event", "classasyncpp_1_1multi__consumer__event.html", "classasyncpp_1_1multi__consumer__event" ],
      [ "mutex", "classasyncpp_1_1mutex.html", "classasyncpp_1_1mutex" ],
      [ "mutex_lock", "classasyncpp_1_1mutex__lock.html", "classasyncpp_1_1mutex__lock" ],
      [ "promise", "classasyncpp_1_1promise.html", "classasyncpp_1_1promise" ],
      [ "promise< void >", "classasyncpp_1_1promise_3_01void_01_4.html", "classasyncpp_1_1promise_3_01void_01_4" ],
      [ "ref", "classasyncpp_1_1ref.html", "classasyncpp_1_1ref" ],
      [ "scope_guard", "classasyncpp_1_1scope__guard.html", "classasyncpp_1_1scope__guard" ],
      [ "scoped_signal_handle", "classasyncpp_1_1scoped__signal__handle.html", null ],
      [ "signal", "classasyncpp_1_1signal.html", null ],
      [ "signal< void(TParams...), TTraits >", "classasyncpp_1_1signal_3_01void_07TParams_8_8_8_08_00_01TTraits_01_4.html", null ],
      [ "signal_handle", "classasyncpp_1_1signal__handle.html", null ],
      [ "signal_manager", "classasyncpp_1_1signal__manager.html", null ],
      [ "signal_manager< TEventType, void(TParams...), TTraits >", "classasyncpp_1_1signal__manager_3_01TEventType_00_01void_07TParams_8_8_8_08_00_01TTraits_01_4.html", null ],
      [ "signal_traits_mt", "structasyncpp_1_1signal__traits__mt.html", null ],
      [ "signal_traits_st", "structasyncpp_1_1signal__traits__st.html", "structasyncpp_1_1signal__traits__st" ],
      [ "simple_dispatcher", "classasyncpp_1_1simple__dispatcher.html", "classasyncpp_1_1simple__dispatcher" ],
      [ "single_consumer_auto_reset_event", "classasyncpp_1_1single__consumer__auto__reset__event.html", "classasyncpp_1_1single__consumer__auto__reset__event" ],
      [ "single_consumer_event", "classasyncpp_1_1single__consumer__event.html", "classasyncpp_1_1single__consumer__event" ],
      [ "task", "classasyncpp_1_1task.html", "classasyncpp_1_1task" ],
      [ "thread_pool", "classasyncpp_1_1thread__pool.html", "classasyncpp_1_1thread__pool" ],
      [ "thread_safe_refcount", "structasyncpp_1_1thread__safe__refcount.html", null ],
      [ "thread_unsafe_refcount", "structasyncpp_1_1thread__unsafe__refcount.html", null ],
      [ "threadsafe_queue", "classasyncpp_1_1threadsafe__queue.html", "classasyncpp_1_1threadsafe__queue" ],
      [ "timer", "classasyncpp_1_1timer.html", "classasyncpp_1_1timer" ]
    ] ]
];